name: Build package aapt

on:
  push:
    paths:
      - '.github/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Reason'     
        required: false
        default: 'update package'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: "/opt/termux/android-sdk"
      NDK: "/opt/termux/android-ndk"

    strategy:
      matrix:
        target_arch: [aarch64, arm]
      fail-fast: false
    steps:
      - name: Clone termux-packages repository
        run: git clone https://github.com/termux/termux-packages .

      - name: Build aapt package
        run: ./scripts/run-docker.sh ./build-package.sh -a ${{ matrix.target_arch }} aapt

      - name: Prepare artifacts
        run: |
          cd output
          for pkg in *.deb; do ar p $pkg data.tar.xz | tar xJf - --strip-components=6 ./data/data/com.termux/files/usr/bin/aapt2; done

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: aapt-${{ matrix.target_arch }}-${{ github.sha }}
          path: output/bin/
